services:
  web:
    build: .
    container_name: nodo-web
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    env_file:
      - .env.production
    restart: unless-stopped
    networks:
      - nodo-network
    mem_limit: 400m
    memswap_limit: 600m

  nginx:
    image: nginx:alpine
    container_name: nodo-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./staticfiles:/staticfiles:ro
      - ./media:/media:ro
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - nodo-network

networks:
  nodo-network:
    driver: bridge
